//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lykke.Job.Messages.Services.Email.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lykke.Job.Messages.Services.Email.Resources.EmailResources", typeof(EmailResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit funds.
        /// </summary>
        internal static string BankCashIn_Subject {
            get {
                return ResourceManager.GetString("BankCashIn_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful cash out.
        /// </summary>
        internal static string Cash_out_no_refund_subject {
            get {
                return ResourceManager.GetString("Cash_out_no_refund_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit {0}.
        /// </summary>
        internal static string CashIn_Subject {
            get {
                return ResourceManager.GetString("CashIn_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KYC verification.
        /// </summary>
        internal static string DeclinedDocuments_Subject {
            get {
                return ResourceManager.GetString("DeclinedDocuments_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit BTC.
        /// </summary>
        internal static string Deposit_done_Subject {
            get {
                return ResourceManager.GetString("Deposit_done_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit {0}.
        /// </summary>
        internal static string Deposit_no_refund_done_subject {
            get {
                return ResourceManager.GetString("Deposit_no_refund_done_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your email.
        /// </summary>
        internal static string EmailConfirmation_Subject {
            get {
                return ResourceManager.GetString("EmailConfirmation_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lykke] Failed transaction.
        /// </summary>
        internal static string FailedTransaction_Subject {
            get {
                return ResourceManager.GetString("FailedTransaction_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash out request processed.
        /// </summary>
        internal static string GenerateSwiftCashoutProcessed_Subject {
            get {
                return ResourceManager.GetString("GenerateSwiftCashoutProcessed_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lykke coins.
        /// </summary>
        internal static string LykkeCoins_name {
            get {
                return ResourceManager.GetString("LykkeCoins_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Lykke Coins.
        /// </summary>
        internal static string MyLykkeCashIn_Subject {
            get {
                return ResourceManager.GetString("MyLykkeCashIn_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful cash out.
        /// </summary>
        internal static string OrdinaryCashOut_done_Subject {
            get {
                return ResourceManager.GetString("OrdinaryCashOut_done_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private wallet address.
        /// </summary>
        internal static string PrivateWalletAddress_Subject {
            get {
                return ResourceManager.GetString("PrivateWalletAddress_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Wallet Backup.
        /// </summary>
        internal static string PrivateWalletBackup_Subject {
            get {
                return ResourceManager.GetString("PrivateWalletBackup_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        internal static string Rejected_Subject {
            get {
                return ResourceManager.GetString("Rejected_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind password.
        /// </summary>
        internal static string RemindPassword_Subject {
            get {
                return ResourceManager.GetString("RemindPassword_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for document.
        /// </summary>
        internal static string RequestForDocument_Subject {
            get {
                return ResourceManager.GetString("RequestForDocument_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolarCoin cash out.
        /// </summary>
        internal static string SolarCashOut_Subject {
            get {
                return ResourceManager.GetString("SolarCashOut_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit SolarCoin.
        /// </summary>
        internal static string SolarCoinAddress_Subject {
            get {
                return ResourceManager.GetString("SolarCoinAddress_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful trade.
        /// </summary>
        internal static string Swap_done_Subject {
            get {
                return ResourceManager.GetString("Swap_done_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash out request.
        /// </summary>
        internal static string SwiftCashOutRequest_Subject {
            get {
                return ResourceManager.GetString("SwiftCashOutRequest_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT cash out request.
        /// </summary>
        internal static string SwiftConfirmed_subject {
            get {
                return ResourceManager.GetString("SwiftConfirmed_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit complete.
        /// </summary>
        internal static string TransferCompleted_Subject {
            get {
                return ResourceManager.GetString("TransferCompleted_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KYC] User registered.
        /// </summary>
        internal static string UserRegistered_Subject {
            get {
                return ResourceManager.GetString("UserRegistered_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Lykke!.
        /// </summary>
        internal static string Welcome_Subject {
            get {
                return ResourceManager.GetString("Welcome_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Lykke FX trading!.
        /// </summary>
        internal static string WelcomeFx_Subject {
            get {
                return ResourceManager.GetString("WelcomeFx_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal request.
        /// </summary>
        internal static string WithdrawalRequest_Subject {
            get {
                return ResourceManager.GetString("WithdrawalRequest_Subject", resourceCulture);
            }
        }
    }
}
